[package]
name = "seven-fm"
version = "0.5.0"
description = "SEVEN.FM - Retro-Futuristic Cyberpunk Terminal Music Player"
authors = ["NeekhillP"]
edition = "2021"

[lib]
name = "seven_fm_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-global-shortcut = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
